const seed={accounts:[{id:1,name:"Cash App",balance:840},{id:2,name:"Checking",balance:1920},{id:3,name:"Savings",balance:1000},{id:4,name:"Efectivo",balance:82.6}],transactions:[{id:1,name:"Paycheck",category:"Ingreso",amount:2125,type:"income",account:2,date:"2026-08-18"},{id:2,name:"Walmart",category:"Comida",amount:86.42,type:"expense",account:2,date:"2026-08-18"},{id:3,name:"Gas",category:"Transporte",amount:44.10,type:"expense",account:1,date:"2026-08-17"},{id:4,name:"Phone Bill",category:"Suscripciones",amount:98,type:"expense",account:2,date:"2026-08-16"},{id:5,name:"Amazon",category:"Shopping",amount:125.30,type:"expense",account:1,date:"2026-08-14"}],budgets:[{id:1,name:"Comida",limit:500},{id:2,name:"Transporte",limit:300},{id:3,name:"Shopping",limit:400},{id:4,name:"Gaming",limit:200}],bills:[{id:1,name:"Phone",amount:98,due:21,paid:false},{id:2,name:"Internet",amount:85,due:24,paid:false},{id:3,name:"Car Insurance",amount:210,due:28,paid:false}],goals:[{id:1,name:"Emergency Fund",target:3000,current:1000}],debts:[{id:1,name:"Credit Card",balance:1420,payment:300}]};
let d=JSON.parse(localStorage.getItem("fraiV2"))||structuredClone(seed),flt="all",typ="expense";const $=id=>document.getElementById(id),fmt=n=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(n);
function save(){localStorage.setItem("fraiV2",JSON.stringify(d));render()}
function totals(){let balance=d.accounts.reduce((s,x)=>s+x.balance,0),income=d.transactions.filter(x=>x.type==="income").reduce((s,x)=>s+x.amount,0),expense=d.transactions.filter(x=>x.type==="expense").reduce((s,x)=>s+x.amount,0),bills=d.bills.filter(x=>!x.paid).reduce((s,x)=>s+x.amount,0),goal=d.goals.reduce((s,x)=>s+x.current,0),debt=d.debts.reduce((s,x)=>s+x.payment,0);return{balance,income,expense,bills,goal,debt,safe:balance-bills-goal-debt}}
function render(){let t=totals();$("safe").textContent=fmt(t.safe);$("bal").textContent=fmt(t.balance);$("hbills").textContent=fmt(t.bills);$("hsave").textContent=fmt(t.goal);$("hdebt").textContent=fmt(t.debt);$("inc").textContent=fmt(t.income);$("exp").textContent=fmt(t.expense);$("pendingBills").textContent=fmt(t.bills);renderAccounts();renderTransactions();renderRecent();renderChart();renderBudgets();renderBills();renderGoals();renderDebts()}
function renderAccounts(){$("accounts").innerHTML=d.accounts.map(x=>`<div class="account"><small>${x.name}</small><b>${fmt(x.balance)}</b></div>`).join("")}
function txrow(x,actions=true){return `<div class="row"><div class="ico">${x.type==="income"?"↙":"↗"}</div><div class="info"><b>${x.name}</b><small>${x.category} · ${x.date}</small></div><div class="amt ${x.type==="income"?"pos":"neg"}">${x.type==="income"?"+":"−"}${fmt(x.amount)}</div>${actions?`<div class="actions"><button onclick="editTx(${x.id})">✎</button><button onclick="deleteTx(${x.id})">×</button></div>`:""}</div>`}
function renderRecent(){$("recent").innerHTML=d.transactions.slice().sort((a,b)=>b.id-a.id).slice(0,4).map(x=>txrow(x,false)).join("")}
function renderTransactions(){let q=($("search")?.value||"").toLowerCase(),a=d.transactions.filter(x=>(flt==="all"||x.type===flt)&&(x.name.toLowerCase().includes(q)||x.category.toLowerCase().includes(q)));$("txList").innerHTML=a.slice().sort((a,b)=>b.id-a.id).map(x=>txrow(x)).join("")||`<div class="privacy">No encontré movimientos.</div>`}
function renderChart(){let cats={};d.transactions.filter(x=>x.type==="expense").forEach(x=>cats[x.category]=(cats[x.category]||0)+x.amount);let entries=Object.entries(cats).sort((a,b)=>b[1]-a[1]),total=entries.reduce((s,x)=>s+x[1],0);$("donutTotal").textContent=fmt(total);let cols=["#f2f3f5","#aab6ff","#9fe0ba","#e8b4b4","#d5c79f","#9ec8df"],start=0,parts=[];entries.forEach((x,i)=>{let end=start+(total?x[1]/total*100:0);parts.push(`${cols[i%cols.length]} ${start}% ${end}%`);start=end});$("donut").style.background=parts.length?`conic-gradient(${parts.join(",")})`:"#242b36";$("legend").innerHTML=entries.slice(0,5).map((x,i)=>`<div class="leg" style="--c:${cols[i%cols.length]}"><span>${x[0]}</span><b>${fmt(x[1])}</b></div>`).join("")}
function spent(cat){return d.transactions.filter(x=>x.type==="expense"&&x.category===cat).reduce((s,x)=>s+x.amount,0)}
function renderBudgets(){let lim=d.budgets.reduce((s,x)=>s+x.limit,0),sp=d.budgets.reduce((s,x)=>s+spent(x.name),0);$("budgetRemain").textContent=fmt(Math.max(0,lim-sp));$("budgetSub").textContent=`${fmt(sp)} gastado de ${fmt(lim)}`;$("overallBar").style.width=Math.min(100,lim?sp/lim*100:0)+"%";$("budgets").innerHTML=d.budgets.map(x=>{let s=spent(x.name),p=Math.min(100,s/x.limit*100);return `<div class="budgetCard"><div class="cardTop"><b>${x.name}</b><button onclick="deleteItem('budgets',${x.id})">×</button></div><div class="bar"><i style="width:${p}%"></i></div><div class="subline"><span>${fmt(s)} gastado</span><span>${fmt(x.limit)} límite</span></div></div>`}).join("")}
function renderBills(){let days=Array.from({length:31},(_,i)=>i+1);$("calendar").innerHTML=days.map(n=>`<div class="day ${d.bills.some(x=>x.due===n&&!x.paid)?"has":""}">${n}</div>`).join("");$("billsList").innerHTML=d.bills.slice().sort((a,b)=>a.due-b.due).map(x=>`<div class="row ${x.paid?"billPaid":""}"><div class="ico">🧾</div><div class="info"><b>${x.name}</b><small>Vence Aug ${x.due}</small></div><div class="amt">${fmt(x.amount)}</div><div class="actions"><button onclick="toggleBill(${x.id})">${x.paid?"↺":"✓"}</button><button onclick="deleteItem('bills',${x.id})">×</button></div></div>`).join("");$("billPreview").innerHTML=d.bills.filter(x=>!x.paid).slice().sort((a,b)=>a.due-b.due).slice(0,3).map(x=>`<div class="row"><div class="ico">🧾</div><div class="info"><b>${x.name}</b><small>Due Aug ${x.due}</small></div><div class="amt">${fmt(x.amount)}</div></div>`).join("")}
function renderGoals(){$("goalsList").innerHTML=d.goals.map(x=>`<div class="goalCard"><div class="cardTop"><b>🎯 ${x.name}</b><button onclick="deleteItem('goals',${x.id})">×</button></div><div class="bar"><i style="width:${Math.min(100,x.current/x.target*100)}%"></i></div><div class="subline"><span>${fmt(x.current)} ahorrado</span><span>Meta ${fmt(x.target)}</span></div><button class="primary" onclick="addGoalMoney(${x.id})">Agregar ahorro</button></div>`).join("")||'<div class="privacy">No tienes metas todavía.</div>'}
function renderDebts(){$("debtsList").innerHTML=d.debts.map(x=>`<div class="debtCard"><div class="cardTop"><b>💳 ${x.name}</b><button onclick="deleteItem('debts',${x.id})">×</button></div><strong style="font-size:25px">${fmt(x.balance)}</strong><div class="subline"><span>Balance</span><span>Pago reservado ${fmt(x.payment)}</span></div></div>`).join("")||'<div class="privacy">No tienes deudas registradas.</div>'}
function go(p){document.querySelectorAll(".page").forEach(x=>x.classList.remove("active"));$(p).classList.add("active");document.querySelectorAll(".nav").forEach(x=>x.classList.toggle("active",x.dataset.p===p));window.scrollTo(0,0);render()}
function modal(title,body){$("modalTitle").textContent=title;$("modalBody").innerHTML=body;$("modal").classList.add("open")}function closeModal(){$("modal").classList.remove("open")}
function accountOptions(sel){return d.accounts.map(a=>`<option value="${a.id}" ${a.id===sel?"selected":""}>${a.name}</option>`).join("")}
function openTx(id){let x=id?d.transactions.find(z=>z.id===id):null;typ=x?.type||"expense";modal(x?"Editar movimiento":"Nuevo movimiento",`<div class="seg"><button id="eBtn" class="${typ==="expense"?"active":""}" onclick="setType('expense')">Gasto</button><button id="iBtn" class="${typ==="income"?"active":""}" onclick="setType('income')">Ingreso</button></div><label>Monto<input id="mAmount" type="number" value="${x?.amount||""}" placeholder="0.00"></label><label>Descripción<input id="mName" value="${x?.name||""}" placeholder="Ej. Walmart"></label><label>Categoría<select id="mCat">${["Comida","Casa","Transporte","Shopping","Gaming","Suscripciones","Deudas","Ahorros","Otros"].map(c=>`<option ${x?.category===c?"selected":""}>${c}</option>`).join("")}</select></label><label>Cuenta<select id="mAcc">${accountOptions(x?.account)}</select></label><button class="primary" onclick="saveTx(${id||0})">Guardar</button>`)}
function setType(t){typ=t;$("eBtn").classList.toggle("active",t==="expense");$("iBtn").classList.toggle("active",t==="income")}
function saveTx(id){let amount=+$("mAmount").value,name=$("mName").value.trim(),account=+$("mAcc").value;if(!amount||!name)return toast("Completa monto y descripción");if(id){let old=d.transactions.find(x=>x.id===id),oa=d.accounts.find(a=>a.id===old.account);oa.balance+=old.type==="expense"?old.amount:-old.amount;Object.assign(old,{name,amount,account,type:typ,category:typ==="income"?"Ingreso":$("mCat").value});let na=d.accounts.find(a=>a.id===account);na.balance+=typ==="income"?amount:-amount}else{d.transactions.push({id:Date.now(),name,amount,account,type:typ,category:typ==="income"?"Ingreso":$("mCat").value,date:new Date().toISOString().slice(0,10)});d.accounts.find(a=>a.id===account).balance+=typ==="income"?amount:-amount}closeModal();save();toast("Movimiento guardado")}
function editTx(id){openTx(id)}function deleteTx(id){if(!confirm("¿Eliminar este movimiento?"))return;let x=d.transactions.find(z=>z.id===id),a=d.accounts.find(z=>z.id===x.account);a.balance+=x.type==="expense"?x.amount:-x.amount;d.transactions=d.transactions.filter(z=>z.id!==id);save()}
function openAccount(){modal("Nueva cuenta",`<label>Nombre<input id="aName" placeholder="Cash App"></label><label>Balance<input id="aBal" type="number" placeholder="0.00"></label><button class="primary" onclick="saveAccount()">Agregar cuenta</button>`)}function saveAccount(){let n=$("aName").value.trim(),b=+$("aBal").value||0;if(!n)return toast("Escribe un nombre");d.accounts.push({id:Date.now(),name:n,balance:b});closeModal();save()}
function openBudget(){modal("Nuevo presupuesto",`<label>Categoría<select id="bName">${["Comida","Casa","Transporte","Shopping","Gaming","Suscripciones","Deudas","Ahorros","Otros"].map(x=>`<option>${x}</option>`).join("")}</select></label><label>Límite mensual<input id="bLimit" type="number" placeholder="500"></label><button class="primary" onclick="saveBudget()">Guardar</button>`)}function saveBudget(){let n=$("bName").value,l=+$("bLimit").value;if(!l)return toast("Escribe un límite");let old=d.budgets.find(x=>x.name===n);old?old.limit=l:d.budgets.push({id:Date.now(),name:n,limit:l});closeModal();save()}
function openBill(){modal("Nuevo bill",`<label>Nombre<input id="billName" placeholder="Internet"></label><div class="two"><label>Monto<input id="billAmt" type="number"></label><label>Día de pago<input id="billDue" type="number" min="1" max="31"></label></div><button class="primary" onclick="saveBill()">Agregar bill</button>`)}function saveBill(){let n=$("billName").value.trim(),a=+$("billAmt").value,du=+$("billDue").value;if(!n||!a||du<1||du>31)return toast("Completa los datos");d.bills.push({id:Date.now(),name:n,amount:a,due:du,paid:false});closeModal();save()}function toggleBill(id){let x=d.bills.find(z=>z.id===id);x.paid=!x.paid;save()}
function openGoal(){modal("Nueva meta",`<label>Nombre<input id="gName" placeholder="Emergency Fund"></label><div class="two"><label>Meta<input id="gTarget" type="number"></label><label>Ya ahorrado<input id="gCurrent" type="number"></label></div><button class="primary" onclick="saveGoal()">Crear meta</button>`)}function saveGoal(){let n=$("gName").value.trim(),t=+$("gTarget").value,c=+$("gCurrent").value||0;if(!n||!t)return toast("Completa la meta");d.goals.push({id:Date.now(),name:n,target:t,current:c});closeModal();save()}function addGoalMoney(id){let x=d.goals.find(z=>z.id===id),v=+prompt("¿Cuánto quieres agregar?",0);if(v>0){x.current+=v;save()}}
function openDebt(){modal("Nueva deuda",`<label>Nombre<input id="dName" placeholder="Credit Card"></label><div class="two"><label>Balance<input id="dBal" type="number"></label><label>Pago reservado<input id="dPay" type="number"></label></div><button class="primary" onclick="saveDebt()">Agregar deuda</button>`)}function saveDebt(){let n=$("dName").value.trim(),b=+$("dBal").value,p=+$("dPay").value||0;if(!n||!b)return toast("Completa la deuda");d.debts.push({id:Date.now(),name:n,balance:b,payment:p});closeModal();save()}
function deleteItem(k,id){if(confirm("¿Eliminar?")){d[k]=d[k].filter(x=>x.id!==id);save()}}function filterTx(f,b){flt=f;document.querySelectorAll(".chip").forEach(x=>x.classList.remove("active"));b.classList.add("active");renderTransactions()}
function exportData(){let a=document.createElement("a"),u=URL.createObjectURL(new Blob([JSON.stringify(d,null,2)],{type:"application/json"}));a.href=u;a.download="frai-finance-v2-backup.json";a.click();URL.revokeObjectURL(u)}function resetDemo(){if(confirm("¿Restaurar demo V2?")){d=structuredClone(seed);save()}}function toast(s){$("toast").textContent=s;$("toast").classList.add("show");setTimeout(()=>$("toast").classList.remove("show"),1700)}render();