const KEY="fraiFinanceLimeV3";let d=JSON.parse(localStorage.getItem(KEY))||{accounts:[],transactions:[],bills:[],savings:0};let filter="all",type="expense",statsPeriod="week",weekOffset=0;if(d.weeklyFund==null)d.weeklyFund=0;const $=x=>document.getElementById(x),money=n=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(n||0);
function totals(){let balance=d.accounts.reduce((s,x)=>s+x.balance,0),inc=d.transactions.filter(x=>x.type==="income").reduce((s,x)=>s+x.amount,0),exp=d.transactions.filter(x=>x.type==="expense").reduce((s,x)=>s+x.amount,0),bills=d.bills.filter(x=>!x.paid).reduce((s,x)=>s+x.amount,0);return{balance,inc,exp,bills,available:balance-bills-d.savings}}
function persist(){localStorage.setItem(KEY,JSON.stringify(d));render()}
function render(){let t=totals();$("balance").textContent=money(t.balance);$("available").textContent=money(t.available);$("income").textContent=money(t.inc);$("expenses").textContent=money(t.exp);$("savings").textContent=money(d.savings);$("totalFlow").textContent=money(t.inc+t.exp);$("pending").textContent=money(t.bills);$("saveReserve").textContent=money(d.savings)+" ›";renderAccounts();renderTx();renderRecent();renderBills();renderWeeklyBills();renderStats();renderSpark()}
function renderAccounts(){let el=$("accountList");el.innerHTML=d.accounts.map(a=>`<div class="accountRow"><div class="icon">▣</div><div class="info"><b>${a.name}</b><small>${a.type||"Account"}</small></div><div class="money">${money(a.balance)}</div></div>`).join("")}
function row(x,actions=true){return `<div class="tx"><div class="icon">${x.type==="income"?"↓":"↑"}</div><div class="info"><b>${x.name}</b><small>${x.category} · ${x.date}</small></div><div class="money ${x.type==="income"?"positive":"negative"}">${x.type==="income"?"+":"−"}${money(x.amount)}</div>${actions?`<button onclick="deleteTx(${x.id})" style="border:0;background:none;color:#666">×</button>`:""}</div>`}
function renderRecent(){let a=[...d.transactions].sort((a,b)=>b.id-a.id).slice(0,4);$("recent").innerHTML=a.length?a.map(x=>row(x,false)).join(""):`<div class="empty"><div class="emptyIcon">▤</div><b>No transactions yet</b><small>Add your first transaction to get started.</small></div>`}
function renderTx(){let q=($("search")?.value||"").toLowerCase(),a=d.transactions.filter(x=>(filter==="all"||x.type===filter)&&(x.name.toLowerCase().includes(q)||x.category.toLowerCase().includes(q))).sort((a,b)=>b.id-a.id);$("txList").innerHTML=a.length?a.map(x=>row(x)).join(""):`<div class="empty"><div class="emptyIcon">＋</div><b>No transactions yet</b><small>Your income and expenses will appear here.</small></div>`}
function renderBills(){$("billList").innerHTML=d.bills.length?d.bills.map(x=>`<div class="billRow" style="${x.paid?"opacity:.45":""}"><div class="icon">▣</div><div class="info"><b>${x.name}</b><small>Due day ${x.due}</small></div><div class="money">${money(x.amount)}</div><button onclick="toggleBill(${x.id})">${x.paid?"↺":"✓"}</button><button onclick="deleteBill(${x.id})">×</button></div>`).join(""):`<div class="empty"><div class="emptyIcon">▣</div><b>No bills yet</b><small>Add your monthly bills here.</small></div>`}
function startOfWeek(date){let x=new Date(date),day=x.getDay(),diff=(day+6)%7;x.setHours(0,0,0,0);x.setDate(x.getDate()-diff);return x}
function periodBounds(){let now=new Date(),s,e,label;if(statsPeriod==="week"){s=startOfWeek(now);s.setDate(s.getDate()+weekOffset*7);e=new Date(s);e.setDate(e.getDate()+7);let last=new Date(e);last.setDate(last.getDate()-1);label=weekOffset===0?"This Week":`${s.toLocaleDateString("en-US",{month:"short",day:"numeric"})} – ${last.toLocaleDateString("en-US",{month:"short",day:"numeric"})}`}else if(statsPeriod==="month"){s=new Date(now.getFullYear(),now.getMonth(),1);e=new Date(now.getFullYear(),now.getMonth()+1,1);label="This Month"}else{s=new Date(now.getFullYear(),0,1);e=new Date(now.getFullYear()+1,0,1);label=String(now.getFullYear())}return{s,e,label}}
function periodTransactions(){let b=periodBounds();return d.transactions.filter(x=>{let dt=new Date(x.date+"T12:00:00");return dt>=b.s&&dt<b.e})}
function renderStats(){let arrTx=periodTransactions(),inc=arrTx.filter(x=>x.type==="income").reduce((s,x)=>s+x.amount,0),exp=arrTx.filter(x=>x.type==="expense").reduce((s,x)=>s+x.amount,0);$("periodLabel").textContent=periodBounds().label;$("weekRange").textContent=periodBounds().label;$("weekNav").style.display=statsPeriod==="week"?"flex":"none";$("periodSpent").textContent=money(exp);$("periodIncome").textContent=money(inc);$("periodLeft").textContent=money(inc-exp);$("income").textContent=money(inc);$("expenses").textContent=money(exp);$("savings").textContent=money(Math.max(inc-exp,0));$("totalFlow").textContent=money(inc+exp);let cats={};arrTx.filter(x=>x.type==="expense").forEach(x=>cats[x.category]=(cats[x.category]||0)+x.amount);let arr=Object.entries(cats).sort((a,b)=>b[1]-a[1]);$("categories").innerHTML=arr.length?arr.map(x=>{let pct=exp?Math.round(x[1]/exp*100):0;return `<div class="cat"><span>${x[0]} <small style="color:#777">${pct}%</small></span><b>${money(x[1])}</b></div>`}).join(""):`<div class="empty"><b>No spending yet</b><small>Add transactions to see where your money is going.</small></div>`;let sum=inc+exp,p=sum?inc/sum*100:0;$("donut").style.background=sum?`conic-gradient(var(--lime) 0 ${p}%,var(--purple) ${p}% 100%)`:"#242624"}
function setPeriod(p,b){statsPeriod=p;if(p!=="week")weekOffset=0;document.querySelectorAll(".periodTabs button").forEach(x=>x.classList.remove("active"));b.classList.add("active");renderStats()}
function shiftWeek(n){weekOffset+=n;renderStats()}
function renderWeeklyBills(){let monthly=d.bills.reduce((s,x)=>s+x.amount,0),weekly=monthly*12/52,fund=+d.weeklyFund||0,pct=weekly?Math.min(100,fund/weekly*100):0;$("weeklyBills").textContent=money(weekly);$("weeklyProgressText").textContent=`${money(fund)} / ${money(weekly)}`;$("weeklyProgressBar").style.width=pct+"%"}
function openWeeklyFund(){let monthly=d.bills.reduce((s,x)=>s+x.amount,0),weekly=monthly*12/52;modal("This Week's Bills Fund",`<label>Amount saved this week<input id="wf" type="number" inputmode="decimal" value="${d.weeklyFund||0}" placeholder="0.00"></label><div class="note">Weekly target: <b style="color:var(--lime)">${money(weekly)}</b></div><button class="primary" onclick="saveWeeklyFund()">Save Progress</button>`)}
function saveWeeklyFund(){d.weeklyFund=+$("wf").value||0;closeModal();persist();toast("Weekly bills fund updated")}
function renderSpark(){let vals=[0],v=0;[...d.transactions].sort((a,b)=>a.id-b.id).forEach(x=>{v+=x.type==="income"?x.amount:-x.amount;vals.push(v)});if(vals.length<2)vals=[0,0];let min=Math.min(...vals),max=Math.max(...vals),range=max-min||1,pts=vals.map((v,i)=>`${i/(vals.length-1)*360},${80-(v-min)/range*65}`).join(" ");$("line").setAttribute("points",pts);$("area").setAttribute("d",`M ${pts.replaceAll(" "," L ")} L 360 90 L 0 90 Z`)}
function go(p){document.querySelectorAll(".page").forEach(x=>x.classList.remove("active"));$(p).classList.add("active");document.querySelectorAll(".nav[data-p]").forEach(x=>x.classList.toggle("active",x.dataset.p===p));scrollTo(0,0);render()}
function modal(title,body){$("mtitle").textContent=title;$("mbody").innerHTML=body;$("modal").classList.add("open")}function closeModal(){$("modal").classList.remove("open")}
function openAccount(){modal("Add Account",`<label>Account name<input id="an" placeholder="Cash App, Checking..."></label><label>Type<select id="at"><option>Checking</option><option>Cash</option><option>Savings</option><option>Credit</option><option>Other</option></select></label><label>Current balance<input id="ab" type="number" inputmode="decimal" placeholder="0.00"></label><button class="primary" onclick="saveAccount()">Add Account</button>`)}
function saveAccount(){let n=$("an").value.trim(),b=+$("ab").value||0;if(!n)return toast("Enter an account name");d.accounts.push({id:Date.now(),name:n,type:$("at").value,balance:b});closeModal();persist()}
function openTx(){if(!d.accounts.length)return toast("Add an account first");type="expense";modal("Add Transaction",`<div class="seg"><button id="ex" class="active" onclick="setType('expense')">Expense</button><button id="in" onclick="setType('income')">Income</button></div><label>Amount<input id="ta" type="number" inputmode="decimal" placeholder="0.00"></label><label>Description<input id="tn" placeholder="Walmart, Paycheck..."></label><label>Category<select id="tc">${["Food","Home","Transportation","Shopping","Gaming","Subscriptions","Debt","Savings","Other"].map(x=>`<option>${x}</option>`).join("")}</select></label><label>Account<select id="tacc">${d.accounts.map(x=>`<option value="${x.id}">${x.name}</option>`).join("")}</select></label><button class="primary" onclick="saveTx()">Add Transaction</button>`)}
function setType(t){type=t;$("ex").classList.toggle("active",t==="expense");$("in").classList.toggle("active",t==="income")}
function saveTx(){let a=+$("ta").value,n=$("tn").value.trim(),id=+$("tacc").value;if(!a||!n)return toast("Complete amount and description");let acc=d.accounts.find(x=>x.id===id);acc.balance+=type==="income"?a:-a;d.transactions.push({id:Date.now(),amount:a,name:n,type,category:type==="income"?"Income":$("tc").value,account:id,date:new Date().toISOString().slice(0,10)});closeModal();persist();toast("Transaction added")}
function deleteTx(id){if(!confirm("Delete transaction?"))return;let x=d.transactions.find(z=>z.id===id),a=d.accounts.find(z=>z.id===x.account);if(a)a.balance+=x.type==="expense"?x.amount:-x.amount;d.transactions=d.transactions.filter(z=>z.id!==id);persist()}
function openBill(){modal("Add Bill",`<label>Name<input id="bn" placeholder="Phone, Internet..."></label><div class="two"><label>Amount<input id="ba" type="number"></label><label>Due day<input id="bd" type="number" min="1" max="31"></label></div><button class="primary" onclick="saveBill()">Add Bill</button>`)}
function saveBill(){let n=$("bn").value.trim(),a=+$("ba").value,du=+$("bd").value;if(!n||!a||du<1||du>31)return toast("Complete bill details");d.bills.push({id:Date.now(),name:n,amount:a,due:du,paid:false});closeModal();persist()}function toggleBill(id){d.bills.find(x=>x.id===id).paid=!d.bills.find(x=>x.id===id).paid;persist()}function deleteBill(id){d.bills=d.bills.filter(x=>x.id!==id);persist()}
function openSavings(){modal("Savings Reserve",`<label>Amount reserved<input id="sv" type="number" value="${d.savings}"></label><button class="primary" onclick="saveSavings()">Save</button>`)}function saveSavings(){d.savings=+$("sv").value||0;closeModal();persist()}
function openTransfer(){if(d.accounts.length<2)return toast("Add at least 2 accounts");modal("Transfer",`<label>From<select id="from">${d.accounts.map(x=>`<option value="${x.id}">${x.name}</option>`).join("")}</select></label><label>To<select id="to">${d.accounts.map(x=>`<option value="${x.id}">${x.name}</option>`).join("")}</select></label><label>Amount<input id="tramt" type="number"></label><button class="primary" onclick="transfer()">Transfer</button>`)}
function transfer(){let f=+$("from").value,t=+$("to").value,a=+$("tramt").value;if(f===t||!a)return toast("Check transfer details");d.accounts.find(x=>x.id===f).balance-=a;d.accounts.find(x=>x.id===t).balance+=a;closeModal();persist();toast("Transfer completed")}
function setFilter(f,b){filter=f;document.querySelectorAll(".chips button").forEach(x=>x.classList.remove("active"));b.classList.add("active");renderTx()}
function clearAll(){if(confirm("Clear ALL your finance data from this device?")){d={accounts:[],transactions:[],bills:[],savings:0,weeklyFund:0};persist();toast("All data cleared")}}
function exportData(){let u=URL.createObjectURL(new Blob([JSON.stringify(d,null,2)],{type:"application/json"})),a=document.createElement("a");a.href=u;a.download="frai-finance-backup.json";a.click();URL.revokeObjectURL(u)}
function toast(s){$("toast").textContent=s;$("toast").classList.add("show");setTimeout(()=>$("toast").classList.remove("show"),1700)}render();